import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import { Carousel, CarouselItem } from 'react-bootstrap';
import axios from 'axios';
import Link from 'next/link';



export default function Home() {

  const [data, setData] = useState();

    const apiKey = "JMK9dEHJzXFtiBa4yWaMia2RQ00L2yaZQZSrax17";
    const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`;

    const getTechTransferData = async () => {
      const res = await axios.get(url);
      const info = await res.data;
      console.log(info);
      setData(info);
    }

    useEffect(() => {
      getTechTransferData();
    }, [])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>


      </Head>

      <main style={{display:'flex', justifyContent:'center', marginLeft:'10%', marginRight:'30%', marginTop:'50%'}}>

        <Link href="/polychromatic">Polychromatic</Link>

    
        
     
      
        {
          data && data.results.map((tech, index) => {
            return (
              <div key={index}>
               
                  {
                    tech && tech.map((t, ind) => {
                      if (ind === 10) {
                        return (
                          <Carousel >
                            <CarouselItem>
                             <Image src={t} width={100}
                              height={100} key={ind} alt={t}/>
                            </CarouselItem>
                          </Carousel>
                          
                        )
                      }
                    })
                  } 
                
              </div>
             
            )
          })
        }
       
    
       
      </main>

     
    </div>
  )
}
